"""Golden-file regression: a fixed strategy on a fixed snapshot, forever.

Spec section 11. The fixture is generated by ``scripts/gen_backtest_golden.py``
from a seeded generator, so it needs no network and no lake, and it deliberately
contains a data gap and a delisting so the awkward paths are covered too.

If one of these fails, the engine's arithmetic has changed. That is sometimes
correct and sometimes a regression, and the difference is a judgement -- so the
fixture is regenerated by hand and the reason goes in the commit message. It is
never regenerated to make a test go green.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import polars as pl
import pytest

REPO = Path(__file__).resolve().parents[2]
SCRIPT = REPO / "scripts" / "gen_backtest_golden.py"
CURVE = REPO / "tests" / "fixtures" / "golden_backtest_curve.parquet"
STATS = REPO / "tests" / "fixtures" / "golden_backtest_stats.json"

sys.path.insert(0, str(REPO / "scripts"))


def rerun():
    from gen_backtest_golden import run

    return run()


# ----------------------------------------------------------------------------------
# The regression itself
# ----------------------------------------------------------------------------------
def test_summary_statistics_are_unchanged() -> None:
    stored = json.loads(STATS.read_text(encoding="utf-8"))
    current = {k: round(v, 12) for k, v in rerun().stats.as_dict().items()}
    assert current == stored, (
        "the engine now computes different numbers for a fixed strategy on fixed "
        "data. If that is intended, regenerate with "
        "`python scripts/gen_backtest_golden.py` and say why in the commit message."
    )


def test_equity_curve_is_unchanged_bar_for_bar() -> None:
    """Summary statistics can coincide while the path differs. The curve is what a
    tearsheet plots, so it is pinned too."""
    stored = pl.read_parquet(CURVE)
    current = rerun().curve
    assert current.columns == stored.columns
    assert current.height == stored.height
    for column in stored.columns:
        if stored.schema[column] == pl.Datetime:
            assert current[column].to_list() == stored[column].to_list()
        else:
            assert current[column].to_numpy() == pytest.approx(
                stored[column].to_numpy(), rel=1e-12, abs=1e-9
            ), f"{column} drifted"


def test_the_check_mode_of_the_generator_agrees() -> None:
    """The generator's own staleness check is what CI would run, so it is exercised
    here rather than trusted."""
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--check"],
        capture_output=True,
        text=True,
        timeout=300,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


# ----------------------------------------------------------------------------------
# Determinism
# ----------------------------------------------------------------------------------
def test_the_same_inputs_produce_byte_identical_results() -> None:
    """Spec section 1: a given commit plus a given snapshot must be reproducible.
    Two runs in one process is the weakest form of that claim, and still worth
    pinning -- an unseeded shuffle or a dict-ordering dependency would fail here."""
    first, second = rerun(), rerun()
    assert first.stats.as_dict() == second.stats.as_dict()
    assert first.curve.equals(second.curve)


# ----------------------------------------------------------------------------------
# What the fixture is supposed to contain
# ----------------------------------------------------------------------------------
def test_the_fixture_exercises_the_awkward_paths() -> None:
    """A golden file over the happy path only would pass while delisting or
    staleness handling was completely broken."""
    result = rerun()
    assert result.data_quality["delisted_symbols"] == 1
    assert result.data_quality["forward_filled_cells"] > 0
    assert result.data_quality["execution"] == "next_open"


def test_the_fixture_books_balance() -> None:
    result = rerun()
    assert result.reconciliation.bars_checked == result.stats.bars - 1
    assert abs(result.reconciliation.worst_absolute_gap) < 0.01


def test_the_fixture_strategy_actually_trades() -> None:
    """A golden file for a strategy that never trades would pin nothing about the
    cost model."""
    result = rerun()
    assert result.stats.turnover_annual > 1.0
    assert result.stats.cost_drag_bps_annual > 10.0
    decomposition = result.cost_decomposition_bps_annual()
    assert decomposition["spread"] > 0
    assert decomposition["impact"] > 0
    assert decomposition["borrow"] > 0


def test_costs_are_what_turns_this_strategy_negative() -> None:
    """Not an accident of the fixture -- it is the point of it. A cross-sectional
    reversal rebalanced monthly on a 1,600%-turnover book is roughly flat gross and
    firmly negative net, which is exactly the gap this platform exists to show."""
    result = rerun()
    assert result.stats.sharpe_gross_undeflated > result.stats.sharpe_undeflated
    assert result.stats.sharpe_undeflated < 0
